version: "3"
services:
    mail:
        image: astzweig/wildduck
        deploy:
            labels:
                traefik.enable: "true"
                traefik.http.services.encrypt0_wildduck.loadbalancer.server.port: 80
                traefik.http.routers.encrypt0_wildduck.tls: "true"
                traefik.http.routers.encrypt0_wildduck.rule: Host(`wildduck.encrypt0.com`)
                traefik.http.routers.encrypt0_wildduck.entrypoints: https
                traefik.http.routers.encrypt0_wildduck.tls.certresolver: route53_resolver
        expose:
            - 25
            - 443
            - 80
            - 465
            - 993
        networks:
            - backend
            - docker-Traefik_private
        volumes:
            - mailconfig:/etc/nodemailer
        depends_on:
            - redis
            - mongo
        environment:
            - FQDN=wildduck.encrypt0.com
            - MAIL_DOMAIN=encrypt0.com
            - API_USE_HTTPS=true
            - API_URL=https://wildduck.encrypt0.com
            - API_TOKEN_SECRET=tLbL8vRwseBsZXQb
    redis:
        image: redis:alpine
        volumes:
            - redis_backup:/data
        networks:
            - backend
    
    mongo:
        image: mongo
        volumes:
            - mongodbs:/data/db
        networks:
            - backend

networks:
    backend:
    docker-Traefik_private:
        external: true
    docker-Elk_logging:
        external: true
volumes:
    mailconfig:
    redis_backup:
    mongodbs: